### ISSUE TITLE
AccountListResourceAsm cast from Account to AccountList

### ISSUE THREAD

**Issue by ghost** [chrishenkel/spring-angularjs-tutorial-7#1]
Hi, I follow up by your tutorial. This is really great! Thank you so much!

In 7th tutorial you create AccountListResourceAsm class, which in my case contains a compile issue. Looks like you tried to make "toResource" from "List<Account>", but it's input is just "Account".

I re-write your method for something like

@Override
    public AccountListResource toResource(AccountList accountList) {
        List<AccountResource> resList = new ArrayList<AccountResource>();

```
    for (Account account : accountList.getAccounts()) {
        resList.add(new AccountResourceAsm().toResource(account));
    }

    AccountListResource finalRes = new AccountListResource();
    finalRes.setAccounts(resList);
    return finalRes;
}
```

I think, you should knew about this minor issue :)

**Comment by chrishenkel** [comment]
Hi levo4ka,

Thank you for the kind words, I am happy you found the tutorial helpful!

I haven't found the issue your referring to in the current tutorial repositories, if you do have this issue, I am thinking it could possibly mean that your local version is out of date. To confirm this issue, please make a link to the line of code on the repository where you see there is a problem. 

Thank you!

**Comment by ghost** [comment]
Input method (https://github.com/chrishenkel/spring-angularjs-tutorial-7/blob/master/src/main/java/tutorial/rest/resources/asm/AccountResourceAsm.java#L19)

Used in (https://github.com/chrishenkel/spring-angularjs-tutorial-7/blob/master/src/main/java/tutorial/rest/resources/asm/AccountListResourceAsm.java#L23)

I not sure, that this is a big problem, maybe you right (I have not correct version, but it's doesn't matter, because I'll use this knowledge for another app), because anyway, it was really usefull 12 video! It's the best tutorial for first steps in Spring+Angular. 
P.S. And also a big plus - all framework version is not out-dated)))

**Comment by chrishenkel** [comment]
Hi levo4ka,

This compiles fine on my machine. AccountListResourceAsm is using AccountResourceAsm indirectly through a base class method, check out https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/mvc/ResourceAssemblerSupport.java#L61 

I think whatever is causing your issue is most likely something else, let me know if you have any more clues as to what is going wrong, and I'll see what I can do.

**Comment by ghost** [comment]
Ha! It's definitely my fault! I used "toResource" instead of "toResources" function.
Sorry for wasting your time.

Thanks for quick responses, by the way :)

**Comment by chrishenkel** [comment]
Sure Levo4ka, good luck on your project :)
